version: '2'
services:
  filebeat:
    start_on_create: true
    ${scale}
    health_check:
      port: 12345
      interval: 30000
      unhealthy_threshold: 3
      healthy_threshold: 3
      response_timeout: 5000
      strategy: recreate
      initializing_timeout: 120000
      reinitializing_timeout: 120000
      request_line: GET /debug/vars HTTP/1.1